version: "3.9"

services:

  app:
    container_name: onemall-app
    build: .
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html
    environment:
      - LOG_CHANNEL=stderr
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - onemall

  nginx:
    container_name: onemall-nginx
    image: nginx:alpine
    ports:
      - "8010:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - onemall

  mysql:
    container_name: onemall-mysql
    image: mysql:8.0
    ports:
      - "127.0.0.1:3308:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: onemall
      MYSQL_USER: onemall
      MYSQL_PASSWORD: Qm9tuHAtZk1eNgtLWPBRzLnscZlgLtiwP2ZgF8EW
      MYSQL_ROOT_PASSWORD: Qm9tuHAtZk1eNgtLWPBRzLnscZlgLtiwP2ZgF8EW
    volumes:
      - onemall_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - onemall

  phpmyadmin:
    container_name: onemall-phpmyadmin
    image: phpmyadmin:5-apache
    ports:
      - "127.0.0.1:8090:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - onemall

volumes:
  onemall_mysql_data:

networks:
  onemall:
    driver: bridge
