<?php

/**
 * Fixed category icons for the whole system.
 *
 * Icons live in public/icons/ (Lucide SVG downloads).
 * After adding or changing files here, run:
 *   php artisan db:seed --class=IconSeeder
 */
return [
    ['name' => 'Alarm Clock', 'slug' => 'alarm_clock', 'url' => '/icons/alarm-clock.svg', 'sortOrder' => 10],
    ['name' => 'Apple', 'slug' => 'apple', 'url' => '/icons/apple.svg', 'sortOrder' => 20],
    ['name' => 'Bike', 'slug' => 'bike', 'url' => '/icons/bike.svg', 'sortOrder' => 30],
    ['name' => 'Book Image', 'slug' => 'book_image', 'url' => '/icons/book-image.svg', 'sortOrder' => 40],
    ['name' => 'Book User', 'slug' => 'book_user', 'url' => '/icons/book-user.svg', 'sortOrder' => 50],
    ['name' => 'Broom Sparkles', 'slug' => 'broom_sparkles', 'url' => '/icons/broom-sparkles.svg', 'sortOrder' => 60],
    ['name' => 'Cable', 'slug' => 'cable', 'url' => '/icons/cable.svg', 'sortOrder' => 70],
    ['name' => 'Calculator', 'slug' => 'calculator', 'url' => '/icons/calculator.svg', 'sortOrder' => 80],
    ['name' => 'Calendar', 'slug' => 'calendar', 'url' => '/icons/calendar.svg', 'sortOrder' => 90],
    ['name' => 'Cake', 'slug' => 'cake', 'url' => '/icons/cake.svg', 'sortOrder' => 100],
    ['name' => 'Cake Slice', 'slug' => 'cake_slice', 'url' => '/icons/cake-slice.svg', 'sortOrder' => 110],
    ['name' => 'Candy Cane', 'slug' => 'candy_cane', 'url' => '/icons/candy-cane.svg', 'sortOrder' => 120],
    ['name' => 'Cannabis', 'slug' => 'cannabis', 'url' => '/icons/cannabis.svg', 'sortOrder' => 130],
    ['name' => 'Car', 'slug' => 'car', 'url' => '/icons/car.svg', 'sortOrder' => 140],
    ['name' => 'Cat', 'slug' => 'cat', 'url' => '/icons/cat.svg', 'sortOrder' => 150],
    ['name' => 'Cherry', 'slug' => 'cherry', 'url' => '/icons/cherry.svg', 'sortOrder' => 160],
    ['name' => 'Chess Knight', 'slug' => 'chess_knight', 'url' => '/icons/chess-knight.svg', 'sortOrder' => 170],
    ['name' => 'Chess Rook', 'slug' => 'chess_rook', 'url' => '/icons/chess-rook.svg', 'sortOrder' => 180],
    ['name' => 'Circle X', 'slug' => 'circle_x', 'url' => '/icons/circle-x.svg', 'sortOrder' => 190],
    ['name' => 'Croissant', 'slug' => 'croissant', 'url' => '/icons/croissant.svg', 'sortOrder' => 200],
    ['name' => 'Cup Soda', 'slug' => 'cup_soda', 'url' => '/icons/cup-soda.svg', 'sortOrder' => 210],
    ['name' => 'Dessert', 'slug' => 'dessert', 'url' => '/icons/dessert.svg', 'sortOrder' => 220],
    ['name' => 'Donut', 'slug' => 'donut', 'url' => '/icons/donut.svg', 'sortOrder' => 230],
    ['name' => 'Drum', 'slug' => 'drum', 'url' => '/icons/drum.svg', 'sortOrder' => 240],
    ['name' => 'Face Grinning', 'slug' => 'face_grinning', 'url' => '/icons/face-grinning.svg', 'sortOrder' => 250],
    ['name' => 'Face Slightly Smiling', 'slug' => 'face_slightly_smiling', 'url' => '/icons/face-slightly-smiling.svg', 'sortOrder' => 260],
    ['name' => 'Ferris Wheel', 'slug' => 'ferris_wheel', 'url' => '/icons/ferris-wheel.svg', 'sortOrder' => 270],
    ['name' => 'File Text', 'slug' => 'file_text', 'url' => '/icons/file-text.svg', 'sortOrder' => 280],
    ['name' => 'Flag Triangle Left', 'slug' => 'flag_triangle_left', 'url' => '/icons/flag-triangle-left.svg', 'sortOrder' => 290],
    ['name' => 'Footprints', 'slug' => 'footprints', 'url' => '/icons/footprints.svg', 'sortOrder' => 300],
    ['name' => 'Gift', 'slug' => 'gift', 'url' => '/icons/gift.svg', 'sortOrder' => 310],
    ['name' => 'Grape', 'slug' => 'grape', 'url' => '/icons/grape.svg', 'sortOrder' => 320],
    ['name' => 'Handbag', 'slug' => 'handbag', 'url' => '/icons/handbag.svg', 'sortOrder' => 330],
    ['name' => 'Hat Glasses', 'slug' => 'hat_glasses', 'url' => '/icons/hat-glasses.svg', 'sortOrder' => 340],
    ['name' => 'Heart', 'slug' => 'heart', 'url' => '/icons/heart.svg', 'sortOrder' => 350],
    ['name' => 'Helicopter', 'slug' => 'helicopter', 'url' => '/icons/helicopter.svg', 'sortOrder' => 360],
    ['name' => 'Hop', 'slug' => 'hop', 'url' => '/icons/hop.svg', 'sortOrder' => 370],
    ['name' => 'Ice Cream Bowl', 'slug' => 'ice_cream_bowl', 'url' => '/icons/ice-cream-bowl.svg', 'sortOrder' => 380],
    ['name' => 'Image Minus', 'slug' => 'image_minus', 'url' => '/icons/image-minus.svg', 'sortOrder' => 390],
    ['name' => 'Key', 'slug' => 'key', 'url' => '/icons/key.svg', 'sortOrder' => 400],
    ['name' => 'Key Round', 'slug' => 'key_round', 'url' => '/icons/key-round.svg', 'sortOrder' => 410],
    ['name' => 'Library', 'slug' => 'library', 'url' => '/icons/library.svg', 'sortOrder' => 420],
    ['name' => 'Library Big', 'slug' => 'library_big', 'url' => '/icons/library-big.svg', 'sortOrder' => 430],
    ['name' => 'Loader Pinwheel', 'slug' => 'loader_pinwheel', 'url' => '/icons/loader-pinwheel.svg', 'sortOrder' => 440],
    ['name' => 'Lollipop', 'slug' => 'lollipop', 'url' => '/icons/lollipop.svg', 'sortOrder' => 450],
    ['name' => 'Mail', 'slug' => 'mail', 'url' => '/icons/mail.svg', 'sortOrder' => 460],
    ['name' => 'Midi Port', 'slug' => 'midi_port', 'url' => '/icons/midi-port.svg', 'sortOrder' => 470],
    ['name' => 'Milk', 'slug' => 'milk', 'url' => '/icons/milk.svg', 'sortOrder' => 480],
    ['name' => 'Mop Sparkles', 'slug' => 'mop_sparkles', 'url' => '/icons/mop-sparkles.svg', 'sortOrder' => 490],
    ['name' => 'Mountain Snow', 'slug' => 'mountain_snow', 'url' => '/icons/mountain-snow.svg', 'sortOrder' => 500],
    ['name' => 'Mouse', 'slug' => 'mouse', 'url' => '/icons/mouse.svg', 'sortOrder' => 510],
    ['name' => 'Palette', 'slug' => 'palette', 'url' => '/icons/palette.svg', 'sortOrder' => 520],
    ['name' => 'Paper Bag', 'slug' => 'paper_bag', 'url' => '/icons/paper-bag.svg', 'sortOrder' => 530],
    ['name' => 'Party Popper', 'slug' => 'party_popper', 'url' => '/icons/party-popper.svg', 'sortOrder' => 540],
    ['name' => 'Plane', 'slug' => 'plane', 'url' => '/icons/plane.svg', 'sortOrder' => 550],
    ['name' => 'Popcorn', 'slug' => 'popcorn', 'url' => '/icons/popcorn.svg', 'sortOrder' => 560],
    ['name' => 'Printer Check', 'slug' => 'printer_check', 'url' => '/icons/printer-check.svg', 'sortOrder' => 570],
    ['name' => 'Rabbit', 'slug' => 'rabbit', 'url' => '/icons/rabbit.svg', 'sortOrder' => 580],
    ['name' => 'Sailboat', 'slug' => 'sailboat', 'url' => '/icons/sailboat.svg', 'sortOrder' => 590],
    ['name' => 'Save Check', 'slug' => 'save_check', 'url' => '/icons/save-check.svg', 'sortOrder' => 600],
    ['name' => 'Scan Qr Code', 'slug' => 'scan_qr_code', 'url' => '/icons/scan-qr-code.svg', 'sortOrder' => 610],
    ['name' => 'Shelving Unit', 'slug' => 'shelving_unit', 'url' => '/icons/shelving-unit.svg', 'sortOrder' => 620],
    ['name' => 'Shirt', 'slug' => 'shirt', 'url' => '/icons/shirt.svg', 'sortOrder' => 630],
    ['name' => 'Shopping Bag', 'slug' => 'shopping_bag', 'url' => '/icons/shopping-bag.svg', 'sortOrder' => 640],
    ['name' => 'Shopping Cart', 'slug' => 'shopping_cart', 'url' => '/icons/shopping-cart.svg', 'sortOrder' => 650],
    ['name' => 'Shrimp', 'slug' => 'shrimp', 'url' => '/icons/shrimp.svg', 'sortOrder' => 660],
    ['name' => 'Snowflake', 'slug' => 'snowflake', 'url' => '/icons/snowflake.svg', 'sortOrder' => 670],
    ['name' => 'Spool', 'slug' => 'spool', 'url' => '/icons/spool.svg', 'sortOrder' => 680],
    ['name' => 'Sport Shoe', 'slug' => 'sport_shoe', 'url' => '/icons/sport-shoe.svg', 'sortOrder' => 690],
    ['name' => 'Spray Can', 'slug' => 'spray_can', 'url' => '/icons/spray-can.svg', 'sortOrder' => 700],
    ['name' => 'Square Library', 'slug' => 'square_library', 'url' => '/icons/square-library.svg', 'sortOrder' => 710],
    ['name' => 'Star Off', 'slug' => 'star_off', 'url' => '/icons/star-off.svg', 'sortOrder' => 720],
    ['name' => 'Store', 'slug' => 'store', 'url' => '/icons/store.svg', 'sortOrder' => 730],
    ['name' => 'Telescope', 'slug' => 'telescope', 'url' => '/icons/telescope.svg', 'sortOrder' => 740],
    ['name' => 'Thermometer Snowflake', 'slug' => 'thermometer_snowflake', 'url' => '/icons/thermometer-snowflake.svg', 'sortOrder' => 750],
    ['name' => 'Turtle', 'slug' => 'turtle', 'url' => '/icons/turtle.svg', 'sortOrder' => 760],
    ['name' => 'Umbrella', 'slug' => 'umbrella', 'url' => '/icons/umbrella.svg', 'sortOrder' => 770],
    ['name' => 'Utensils', 'slug' => 'utensils', 'url' => '/icons/utensils.svg', 'sortOrder' => 780],
    ['name' => 'Van', 'slug' => 'van', 'url' => '/icons/van.svg', 'sortOrder' => 790],
    ['name' => 'Vegan', 'slug' => 'vegan', 'url' => '/icons/vegan.svg', 'sortOrder' => 800],
    ['name' => 'Warehouse', 'slug' => 'warehouse', 'url' => '/icons/warehouse.svg', 'sortOrder' => 810],
    ['name' => 'Washing Machine', 'slug' => 'washing_machine', 'url' => '/icons/washing-machine.svg', 'sortOrder' => 820],
];
